FROM oven/bun:1

#load env vars
ARG CONVEX_DEPLOYMENT
ARG NEXT_PUBLIC_CONVEX_URL
ARG NEXT_PUBLIC_CONVEX_SITE_URL
ARG SITE_URL

ENV CONVEX_DEPLOYMENT=$CONVEX_DEPLOYMENT
ENV NEXT_PUBLIC_CONVEX_URL=$NEXT_PUBLIC_CONVEX_URL
ENV NEXT_PUBLIC_CONVEX_SITE_URL=$NEXT_PUBLIC_CONVEX_SITE_URL
ENV SITE_URL=$SITE_URL

WORKDIR /app

COPY package.json .
COPY bun.lock .
COPY tsconfig.json .

RUN bun install

COPY . .

RUN bunx convex deploy
RUN bun run build

EXPOSE 3000

CMD ["bun","run", "start"]